name: in-the-mealtime
version: '3.8'

services:
  database:
    image: postgres:16.3@sha256:0aafd2ae7e6c391f39fb6b7621632d79f54068faebc726caf469e87bd1d301c0
    container_name: database
    environment:
      POSTGRES_DB: in_the_mealtime
      POSTGRES_USER: in_the_mealtime_user
      POSTGRES_PASSWORD: in_the_mealtime_pw
    ports:
      - "5432:5432"
    networks:
      - in-the-mealtime
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  in-the-mealtime:

volumes:
  postgres_data:
