@startuml
[*] --> NeueBestellung : Erzeuge

NeueBestellung -->[*]: Löschen

NeueBestellung --> OffeneBestellung : OrderPosition hinzufügen
OffeneBestellung --> OffeneBestellung : OrderPosition hinzufügen oder bearbeiten

OffeneBestellung --> NeueBestellung: Letzte OrderPosition löschen

OffeneBestellung --> GesperrteBestellung : Versuchen zu bestellen
GesperrteBestellung --> OffeneBestellung : Zeitlimit vergangen
GesperrteBestellung --> OffeneBestellung : Manuell wieder eröffnet
GesperrteBestellung --> BestellteBestellung: Bestellung erfolgreich

OffeneBestellung --> ZurückgezogeneBestellung : Zurückziehen
GesperrteBestellung --> ZurückgezogeneBestellung : Zurückziehen
ZurückgezogeneBestellung --> [*] : nach Zeit Ablauf

BestellteBestellung --> EingetroffeneBestellung : Manuelle Benachrichtigung

BestellteBestellung --> ZurückgezogeneBestellung : Manuelles Zurückziehen

BestellteBestellung --> ArchivierteBestellung: nach Zeit Ablauf
EingetroffeneBestellung --> ArchivierteBestellung: nach Zeit Ablauf

ArchivierteBestellung --> [*] : nach Zeit Ablauf

@enduml