ALTER TABLE MEAL_ORDER
    ADD COLUMN LOCKED_AT TIMESTAMP WITH TIME ZONE;

ALTER TABLE MEAL_ORDER
    ADD COLUMN ORDERED_AT TIMESTAMP WITH TIME ZONE;

ALTER TABLE MEAL_ORDER
    ADD COLUMN DELIVERED_AT TIMESTAMP WITH TIME ZONE;

ALTER TABLE MEAL_ORDER
    ADD COLUMN REVOKED_AT TIMESTAMP WITH TIME ZONE;

ALTER TABLE MEAL_ORDER
    ADD COLUMN ARCHIVED_AT TIMESTAMP WITH TIME ZONE;
