ALTER TABLE ORDER_POSITION
    ADD COLUMN TMP_PRICE NUMERIC(18, 2),
    ADD COLUMN TMP_PAID  NUMERIC(18, 2),
    ADD COLUMN TMP_TIP   NUMERIC(18, 2);

UPDATE ORDER_POSITION
SET TMP_PRICE = PRICE::NUMERIC(18, 2),
    TMP_PAID  = PAID::NUMERIC(18, 2),
    TMP_TIP   = TIP::NUMERIC(18, 2);

ALTER TABLE ORDER_POSITION
    DROP COLUMN PRICE,
    DROP COLUMN PAID,
    DROP COLUMN TIP;

ALTER TABLE ORDER_POSITION
    RENAME COLUMN TMP_PRICE TO PRICE;
ALTER TABLE ORDER_POSITION
    RENAME COLUMN TMP_PAID TO PAID;
ALTER TABLE ORDER_POSITION
    RENAME COLUMN TMP_TIP TO TIP;

ALTER TABLE ORDER_POSITION
    ALTER COLUMN PRICE SET NOT NULL;

ALTER TABLE ORDER_POSITION
    ADD CHECK ( PRICE > 0 ),
    ADD CHECK ( PAID IS NULL OR PAID > 0 ),
    ADD CHECK ( TIP IS NULL OR TIP >= 0 );
