CREATE TYPE ORDER_STATE AS ENUM(
    'NEW',
    'OPEN',
    'LOCKED',
    'REVOKED',
    'ORDERED',
    'DELIVERED',
    'ARCHIVED'
);

CREATE TYPE MONEY_COLLECTION_TYPE AS ENUM(
    'BAR',
    'PAY_PAL'
);

CREATE TABLE MEAL_ORDER
(
    ID                   UUID PRIMARY KEY         NOT NULL,
    RESTAURANT_ID        UUID                     NOT NULL REFERENCES RESTAURANT (ID),
    STATE                ORDER_STATE              NOT NULL,

    ORDERER              TEXT,
    FETCHER              TEXT,
    MONEY_COLLECTOR_TYPE MONEY_COLLECTION_TYPE,
    MONEY_COLLECTOR      TEXT,

    ORDER_CLOSING_TIME   TIME,

    VERSION              UUID                     NOT NULL,
    CREATED_AT           TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY           UUID                     NOT NULL,
    UPDATED_AT           TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_BY           UUID                     NOT NULL
);

CREATE INDEX IDX_ORDER_RESTAURANT_ID ON MEAL_ORDER (RESTAURANT_ID);
CREATE INDEX IDX_ORDER_STATE ON MEAL_ORDER (STATE);
