ALTER TABLE MEAL_ORDER
    ADD COLUMN TMP_ORDER_FEE MONEY_TYPE;

UPDATE MEAL_ORDER
SET TMP_ORDER_FEE = ROUND(ORDER_FEE * 100);

ALTER TABLE MEAL_ORDER
    DROP COLUMN ORDER_FEE;
ALTER TABLE MEAL_ORDER
    RENAME COLUMN TMP_ORDER_FEE TO ORDER_FEE;

ALTER TABLE MEAL_ORDER
    ADD CHECK ( ORDER_FEE IS NULL OR (0 <= ORDER_FEE AND ORDER_FEE <= 100000000) );
