ALTER TABLE MEAL_ORDER
    ADD COLUMN RESPONSIBLE_PERSON TEXT;

UPDATE MEAL_ORDER
SET RESPONSIBLE_PERSON = COALESCE(ORDERER, '#unknown');

ALTER TABLE MEAL_ORDER
    ALTER RESPONSIBLE_PERSON SET NOT NULL;
