ALTER TABLE ORDER_POSITION
    ADD COLUMN TMP_PRICE MONEY_TYPE,
    ADD COLUMN TMP_PAID  MONEY_TYPE,
    ADD COLUMN TMP_TIP   MONEY_TYPE;

UPDATE ORDER_POSITION
SET TMP_PRICE = ROUND(PRICE * 100),
    TMP_PAID  = ROUND(PAID * 100),
    TMP_TIP   = ROUND(TIP * 100);

ALTER TABLE ORDER_POSITION
    DROP COLUMN PRICE,
    DROP COLUMN PAID,
    DROP COLUMN TIP;

ALTER TABLE ORDER_POSITION
    RENAME COLUMN TMP_PRICE TO PRICE;
ALTER TABLE ORDER_POSITION
    RENAME COLUMN TMP_PAID TO PAID;
ALTER TABLE ORDER_POSITION
    RENAME COLUMN TMP_TIP TO TIP;

ALTER TABLE ORDER_POSITION
    ALTER COLUMN PRICE SET NOT NULL,
    ADD CONSTRAINT CHK_PRICE_IS_POSITIVE CHECK (PRICE IS NOT NULL AND 0 < PRICE);

ALTER TABLE ORDER_POSITION
    ADD CONSTRAINT CHK_PAID_IS_POSITIVE CHECK (PAID IS NULL OR 0 < PAID),
    ADD CONSTRAINT CHK_TIP_IS_POSITIVE CHECK (TIP IS NULL OR 0 <= TIP);

ALTER TABLE ORDER_POSITION
    ADD CONSTRAINT CHK_PAID_IS_GREATER_THAN_OBLIGATION CHECK ( PRICE + COALESCE(TIP, 0) <= PAID);
