ALTER TABLE RESTAURANT
    ADD COLUMN AVATAR_COLOR TEXT;

UPDATE RESTAURANT
SET AVATAR_COLOR = '#' || SUBSTRING(TO_HEX((FLOOR(RANDOM() * 256 * 256 * 256))::INT) || '000000', 1, 6);

ALTER TABLE RESTAURANT
    ALTER AVATAR_COLOR SET NOT NULL,
    ADD CONSTRAINT CHK_AVATAR_COLOR CHECK ((LENGTH(AVATAR_COLOR) = 6 + 1) AND AVATAR_COLOR ~* '^#([0-9a-f]{6})$');
