ALTER TABLE MEAL_ORDER
    ADD COLUMN ORDER_FEE_TEMP INTEGER;
UPDATE MEAL_ORDER
    SET ORDER_FEE_TEMP = ROUND(ORDER_FEE * 100);
ALTER TABLE MEAL_ORDER
    DROP COLUMN ORDER_FEE;
ALTER TABLE MEAL_ORDER
    RENAME COLUMN ORDER_FEE_TEMP TO ORDER_FEE;

ALTER TABLE ORDER_POSITION
    ADD COLUMN PRICE_TEMP INTEGER,
    ADD COLUMN PAID_TEMP INTEGER,
    ADD COLUMN TIP_TEMP INTEGER;
UPDATE ORDER_POSITION
    SET PRICE_TEMP = ROUND(PRICE * 100),
    SET PAID_TEMP = ROUND(PAID * 100),
    SET TIP_TEMP = ROUND(ORDETIPR_FEE * 100);
ALTER TABLE ORDER_POSITION
    DROP COLUMN PRICE,
    DROP COLUMN PAID,
    DROP COLUMN TIP;
ALTER TABLE ORDER_POSITION
    RENAME COLUMN PRICE_TEMP TO PRICE,
    RENAME COLUMN PAID_TEMP TO PAID,
    RENAME COLUMN TIP_TEMP TO TIP;